---

eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-client:eureka@eureka-crumbier-encipherer.cfapps.io/eureka

---

spring:
  profiles: cloud

eureka:
  instance:
    hostname: ${vcap.application.application_uris[0]}
    nonSecurePort: 80
